services:
  ncat:
    build: .
    env_file:
      - .env.local.minio.n8n
    ports:
      - "8080:8080"
    volumes:
      - storage:/app/storage
      - logs:/app/logs
    restart: unless-stopped
    depends_on:
      - minio
      - minio-init
      - postgres
    networks:
      - nca-network

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - nca-network

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin123;
      /usr/bin/mc mb myminio/nca-toolkit-local --ignore-existing;
      /usr/bin/mc anonymous set public myminio/nca-toolkit-local;
      echo 'MinIO bucket nca-toolkit-local created and configured as public';
      "
    networks:
      - nca-network

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=UTC
      - N8N_SECURE_COOKIE=false
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=n8n_password
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    depends_on:
      - postgres
    networks:
      - nca-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
      - ./models:/models
    ports:
      - "11434:11434"
    networks:
      - nca-network
    environment:
      OLLAMA_HOST: "0.0.0.0"
      OLLAMA_KEEP_ALIVE: "10m"
      OLLAMA_MAX_QUEUE: "1024"
      OLLAMA_NUM_PARALLEL: "4"
      OLLAMA_CONTEXT_LENGTH: "2048"
      OLLAMA_LOAD_TIMEOUT: "10m"
      OLLAMA_FLASH_ATTENTION: "true"
      OLLAMA_GPU_OVERHEAD: "512"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: n8n_user
      POSTGRES_PASSWORD: n8n_password
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nca-network

volumes:
  storage:
    driver: local
  logs:
    driver: local
  minio_data:
    driver: local
  n8n_data:
    driver: local
  ollama_data:
    driver: local
  postgres_data:
    driver: local

networks:
  nca-network:
    driver: bridge
